name: Lint

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "server/crates/**"
      - "server/src/**"
      - "server/.cargo/**"
      - "server/Cargo.toml"
      - "server/Cargo.lock"
      - "server/build.rs"
      - "server/rust-toolchain.toml"
  workflow_dispatch:

env:
  # Disable incremental compilation
  CARGO_INCREMENTAL: 0
  # Disable debuginfo
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  RUSTFLAGS: "-W warnings"

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: Cache Cargo downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}

      - name: Check format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --quiet

      - name: Build test
        run: cargo test --no-run

      - name: Run test
        run: cargo test --quiet
